swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /zonas:
    x-swagger-router-controller: zonas.controller
    get:
      description: das
      operationId: getZonas
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetZonasListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetZonasResponse:
    type: object
    properties:
      id:
        type: number
        description: identifier
      name:
        type: string
        description: Nombre de la zona
    required:
      - name
  GetZonasListResponse:
    required:
      - zonas
    properties:
      zonas:
        type: array
        items:
          $ref: "#/definitions/GetZonasResponse"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
